### ISSUE TITLE
Subsets Not working

### ISSUE THREAD

**Issue by kirtonBCIlab** [kirtonBCIlab/bci-essentials-python#3]
Seem to be an issue with getting the subset call to work with online data. Have resorted to using the main branch at the moment. Will investigate.

Issue was found by both myself and a summer student. WIll try to replicate.

Here is the error - on the "SSVEP-clf" branch:

```
> Traceback (most recent call last):
>   File "d:/Users/BCI-Morpheus/Documents/GitHub/bci-essentials-python/examples/p300_unity_backend.py", line 28, in <module>
>     test_erp.main(online=True, training=True, pp_low=0.1, pp_high=15, pp_order=5, plot_erp=False, window_start=0.0, window_end=0.6, subset=["P3", "P4"])
>   File "d:\Users\BCI-Morpheus\Documents\GitHub\bci-essentials-python\examples\..\bci_essentials\bci_data.py", line 830, in main
>     self.pull_data_from_stream()
>   File "d:\Users\BCI-Morpheus\Documents\GitHub\bci-essentials-python\examples\..\bci_essentials\bci_data.py", line 350, in pull_data_from_stream
>     new_eeg_data = new_eeg_data[:, self.subset_indices]
> AttributeError: 'ERP_data' object has no attribute 'subset_indices'
```

**Comment by kirtonBCIlab** [comment]
I fixed the issue, see latest push on the SSVEP branch.
