### ISSUE TITLE
Empty data output on limited P300 selectable objects

### ISSUE THREAD

**Issue by ekinney-lang** [kirtonBCIlab/bci-essentials-python#34]
I am receiving this error at random points when P300 selection objects are <3.

Trial Started
D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\numpy\core\_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
Trial Ends
making a prediction
Traceback (most recent call last):
  File "D:\Users\Eli\Documents\GitHub\bci-essentials-python\examples\p300_unity_backend.py", line 29, in <module>
    test_erp.main(online=True, training=True, pp_low=0.1, pp_high=10, pp_order=5, plot_erp=False, window_start=0.0, window_end=0.8, print_markers=True, print_training=True, print_fit=True, print_performance=True, print_predict=True)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\bci_essentials\bci_data.py", line 1446, in main
    prediction = self.classifier.predict_decision_block(decision_block=self.decision_blocks_processed[self.decision_count,0:self.num_options,:,:], print_predict=print_predict)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\bci_essentials\classification.py", line 279, in predict_decision_block
    proba_mat = self.clf.predict_proba(decision_block)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\sklearn\pipeline.py", line 523, in predict_proba
    Xt = transform.transform(Xt)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\pyriemann\tangentspace.py", line 147, in transform
    return tangent_space(X, Cr)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\pyriemann\utils\tangentspace.py", line 32, in tangent_space
    tmp = logm(Cm12 @ X @ Cm12)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\pyriemann\utils\base.py", line 70, in logm
    return _matrix_operator(C, np.log)
  File "D:\Users\Eli\Anaconda3\envs\bci-essentials\lib\site-packages\pyriemann\utils\base.py", line 13, in _matrix_operator
    raise ValueError(
ValueError: Matrices must be positive definite. Add regularization to avoid this error.

**Comment by gregbci** [comment]
tracking internally
